In [1]:
from sklearn import datasets, linear_model
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import seaborn as sns
import numpy as np

In [3]:
data = pd.read_csv("/content/drive/MyDrive/csv_file/data1-berasTest.csv")

In [4]:
data.head()

pasar1  pasar2  pasar3  pasar4  pasar5  pasar6  pasar7  pasar8
0    9991    9990    9991    9992    9970    9988    9981    9981
1    9990    9991    9992    9970    9988    9981    9981    9981
2    9991    9992    9970    9988    9981    9981    9981    9973
3    9992    9970    9988    9981    9981    9981    9973    9973
4    9970    9988    9981    9981    9981    9973    9973    9977

In [5]:
data.tail()

pasar1  pasar2  pasar3  pasar4  pasar5  pasar6  pasar7  pasar8
1449   11500   11500   11500   11500   11500   11500   11500   11500
1450   11500   11500   11500   11500   11500   11500   11500   11500
1451   11500   11500   11500   11500   11500   11500   11500   11500
1452   11500   11500   11500   11500   11500   11500   11500   11500
1453   11500   11500   11500   11500   11500   11500   11500   11500

In [6]:
data.columns

Index(['pasar1', 'pasar2', 'pasar3', 'pasar4', 'pasar5', 'pasar6', 'pasar7',
       'pasar8'],
      dtype='object')

In [7]:
data.shape

(1454, 8)

In [8]:
data.describe()

pasar1        pasar2  ...        pasar7        pasar8
count   1454.000000   1454.000000  ...   1454.000000   1454.000000
mean   10664.964237  10666.002063  ...  10671.207703  10672.252407
std      604.630392    604.767817  ...    605.408956    605.527696
min     9748.000000   9748.000000  ...   9748.000000   9748.000000
25%    10370.250000  10371.000000  ...  10374.250000  10375.250000
50%    10500.000000  10500.000000  ...  10500.000000  10500.000000
75%    10900.000000  10900.000000  ...  10923.500000  10933.750000
max    12500.000000  12500.000000  ...  12500.000000  12500.000000

[8 rows x 8 columns]

In [9]:
from sklearn.svm import SVR 
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.model_selection import KFold # import KFold
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report #for checking the  model accuracy

In [10]:
test = data.iloc[:, 0].values
test_1 = data.iloc[:, 1].values
test_2 = data.iloc[:, 2].values
test_3 = data.iloc[:, 3].values
test_4 = data.iloc[:, 4].values
train = data.iloc[:, 1:].values
train_1 = data.iloc[:, [0,2,3,4,5,6,7]].values
train_2 = data.iloc[:, [0,1,3,4,5,6,7]].values
train_3 = data.iloc[:, [0,1,2,4,5,6,7]].values
train_4 = data.iloc[:, [0,1,2,3,5,6,7]].values

In [11]:
test

array([ 9991,  9990,  9991, ..., 11500, 11500, 11500])

In [12]:
train

array([[ 9990,  9991,  9992, ...,  9988,  9981,  9981],
       [ 9991,  9992,  9970, ...,  9981,  9981,  9981],
       [ 9992,  9970,  9988, ...,  9981,  9981,  9973],
       ...,
       [11500, 11500, 11500, ..., 11500, 11500, 11500],
       [11500, 11500, 11500, ..., 11500, 11500, 11500],
       [11500, 11500, 11500, ..., 11500, 11500, 11500]])

In [13]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(train, test, test_size=0.1, random_state=19)
X_train_1, X_test_1, y_train_1, y_test_1 = train_test_split(train_1, test_1, test_size=0.1, random_state=19)
X_train_2, X_test_2, y_train_2, y_test_2 = train_test_split(train_2, test_2, test_size=0.1, random_state=19)
X_train_3, X_test_3, y_train_3, y_test_3 = train_test_split(train_3, test_3, test_size=0.1, random_state=19)
X_train_4, X_test_4, y_train_4, y_test_4 = train_test_split(train_4, test_4, test_size=0.1, random_state=19)

In [14]:
svr = SVR(kernel='rbf')
svr.fit(X_train, y_train)
svr.score(X_test, y_test)

0.4914657973701639

In [15]:
svr_1 = SVR()
svr_1.fit(X_train_1, y_train_1)
svr.score(X_test_1, y_test_1)

0.4876562437481065

In [16]:
svr_2 = SVR()
svr_2.fit(X_train_2, y_train_2)
svr.score(X_test_2, y_test_2)

0.48936882678860083

In [17]:
svr_3 = SVR()
svr_3.fit(X_train_3, y_train_3)
svr.score(X_test_3, y_test_3)

0.4988634644759533

In [18]:
svr_4 = SVR()
svr_4.fit(X_train_4, y_train_4)
svr.score(X_test_4, y_test_4)

0.4845937404821099

In [19]:
pred = svr.predict(X_test)
pred.shape

(146,)

In [20]:
pred_1 = svr.predict(X_test_1)
pred_1.shape

(146,)

In [21]:
pred_2 = svr.predict(X_test_2)
pred_2.shape

(146,)

In [22]:
pred_3 = svr.predict(X_test_3)
pred_3.shape

(146,)

In [23]:
pred_4 = svr.predict(X_test_4)
pred_4.shape

(146,)

In [24]:
pred

array([10431.27548738, 10384.57007849, 10457.6201532 , 10329.51951341,
       10810.29219014, 10462.53322627, 10916.83536619, 10341.61706475,
       10917.23627245, 10890.37394814, 10420.82273644, 10472.10257774,
       10458.35966924, 10428.61415002, 10855.79745839, 10855.79745839,
       10904.32553139, 10499.89999962, 10422.28806095, 10802.49941772,
       10855.79745839, 10499.89999962, 10384.12627495, 10335.13744383,
       10338.75696218, 10831.12357863, 10545.74887734, 10427.08212921,
       10732.02696573, 10499.89999962, 10499.89999962, 10811.14211277,
       10499.89999962, 10337.03439966, 10421.41126012, 10446.34805562,
       10499.89999962, 10831.12357863, 10414.03019044, 10466.66848676,
       10756.34316667, 10670.73792694, 10437.6873246 , 10499.89999962,
       10874.58524656, 10435.4759406 , 10658.75931291, 10441.59426278,
       10426.01761275, 10708.47281637, 10713.52175678, 10335.13744383,
       10365.77024449, 10576.58297657, 10855.79745839, 10499.89999962,
      

In [25]:
pred_1

array([10432.34449534, 10384.57007849, 10456.63365876, 10329.44802976,
       10810.29219014, 10463.61580601, 10913.62855475, 10341.61706475,
       10917.23627245, 10890.3692947 , 10420.3517041 , 10476.9558266 ,
       10459.77283233, 10429.59091768, 10855.79745839, 10855.79745839,
       10904.32553139, 10499.89999962, 10422.10995542, 10802.49941772,
       10855.79745839, 10499.89999962, 10384.12627495, 10335.13744383,
       10339.04380454, 10831.12357863, 10546.60005798, 10427.08212921,
       10732.02696573, 10499.89999962, 10499.89999962, 10802.49941772,
       10499.89999962, 10336.69957349, 10423.21452263, 10448.17297006,
       10499.89999962, 10831.12357863, 10413.58160718, 10465.42148856,
       10754.08963273, 10668.79117558, 10438.81912908, 10499.89999962,
       10874.58524656, 10434.77666658, 10658.75931291, 10444.45692699,
       10426.01761275, 10677.39520189, 10713.98630155, 10360.8471767 ,
       10372.06944064, 10576.70850365, 10855.79745839, 10499.89999962,
      

In [26]:
pred_2

array([10430.93566468, 10385.3155055 , 10451.01109721, 10329.31361907,
       10810.29219014, 10464.54436206, 10913.70864245, 10341.39882398,
       10917.23627245, 10890.41688458, 10419.43172816, 10474.17609449,
       10459.98062285, 10428.26903948, 10855.79745839, 10855.79745839,
       10904.32553139, 10499.89999962, 10420.80496547, 10802.49941772,
       10855.79745839, 10499.89999962, 10384.12627495, 10335.13744383,
       10338.70974016, 10831.12357863, 10545.65371001, 10427.08212921,
       10753.19401506, 10499.89999962, 10499.89999962, 10810.96750869,
       10499.89999962, 10336.94774223, 10423.12492519, 10449.68793707,
       10499.89999962, 10831.12357863, 10414.52241891, 10461.994861  ,
       10753.49108194, 10669.26714327, 10436.14621385, 10499.89999962,
       10874.58524656, 10432.80225211, 10658.75931291, 10443.09313996,
       10426.40501642, 10675.44057566, 10712.96394866, 10360.8471767 ,
       10370.51313349, 10576.70850365, 10855.79745839, 10499.89999962,
      

In [27]:
a = pred.astype(int)
a

array([10431, 10384, 10457, 10329, 10810, 10462, 10916, 10341, 10917,
       10890, 10420, 10472, 10458, 10428, 10855, 10855, 10904, 10499,
       10422, 10802, 10855, 10499, 10384, 10335, 10338, 10831, 10545,
       10427, 10732, 10499, 10499, 10811, 10499, 10337, 10421, 10446,
       10499, 10831, 10414, 10466, 10756, 10670, 10437, 10499, 10874,
       10435, 10658, 10441, 10426, 10708, 10713, 10335, 10365, 10576,
       10855, 10499, 10601, 10433, 10806, 10499, 10835, 10499, 10413,
       10428, 10868, 10346, 10869, 10810, 10346, 10329, 10499, 10342,
       10831, 10426, 10405, 10432, 10887, 10352, 10802, 10384, 10855,
       10499, 10867, 10757, 10348, 10598, 10499, 10855, 10336, 10589,
       10335, 10460, 10334, 10443, 10609, 10419, 10408, 10337, 10438,
       10342, 10448, 10436, 10499, 10539, 10656, 10347, 10630, 10335,
       10462, 10709, 10855, 10494, 10401, 10443, 10499, 10831, 10782,
       10334, 10805, 10335, 10436, 10831, 10384, 10917, 10917, 10764,
       10855, 10855,

In [28]:
b = pred_1.astype(int)
b

array([10432, 10384, 10456, 10329, 10810, 10463, 10913, 10341, 10917,
       10890, 10420, 10476, 10459, 10429, 10855, 10855, 10904, 10499,
       10422, 10802, 10855, 10499, 10384, 10335, 10339, 10831, 10546,
       10427, 10732, 10499, 10499, 10802, 10499, 10336, 10423, 10448,
       10499, 10831, 10413, 10465, 10754, 10668, 10438, 10499, 10874,
       10434, 10658, 10444, 10426, 10677, 10713, 10360, 10372, 10576,
       10855, 10499, 10603, 10432, 10806, 10499, 10835, 10499, 10414,
       10427, 10868, 10346, 10869, 10810, 10346, 10329, 10499, 10342,
       10831, 10426, 10405, 10431, 10887, 10352, 10802, 10384, 10855,
       10462, 10867, 10779, 10348, 10601, 10499, 10805, 10335, 10588,
       10335, 10461, 10334, 10442, 10608, 10418, 10408, 10337, 10436,
       10342, 10450, 10436, 10499, 10536, 10655, 10347, 10627, 10335,
       10462, 10710, 10855, 10493, 10401, 10445, 10499, 10831, 10804,
       10334, 10805, 10335, 10436, 10831, 10382, 10917, 10917, 10764,
       10855, 10855,

In [29]:
e = pred_2.astype(int)
e

array([10430, 10385, 10451, 10329, 10810, 10464, 10913, 10341, 10917,
       10890, 10419, 10474, 10459, 10428, 10855, 10855, 10904, 10499,
       10420, 10802, 10855, 10499, 10384, 10335, 10338, 10831, 10545,
       10427, 10753, 10499, 10499, 10810, 10499, 10336, 10423, 10449,
       10499, 10831, 10414, 10461, 10753, 10669, 10436, 10499, 10874,
       10432, 10658, 10443, 10426, 10675, 10712, 10360, 10370, 10576,
       10855, 10499, 10602, 10432, 10806, 10499, 10835, 10499, 10405,
       10428, 10868, 10345, 10878, 10810, 10347, 10329, 10499, 10342,
       10831, 10426, 10405, 10429, 10887, 10352, 10802, 10382, 10855,
       10462, 10867, 10779, 10349, 10601, 10499, 10805, 10335, 10588,
       10335, 10460, 10334, 10441, 10605, 10418, 10408, 10337, 10437,
       10343, 10450, 10435, 10499, 10536, 10654, 10347, 10627, 10335,
       10432, 10711, 10855, 10493, 10401, 10443, 10499, 10831, 10804,
       10334, 10757, 10335, 10436, 10831, 10382, 10917, 10917, 10764,
       10855, 10855,

In [30]:
f = pred_3.astype(int)
f

array([10430, 10385, 10446, 10329, 10810, 10464, 10909, 10340, 10917,
       10890, 10421, 10470, 10459, 10428, 10855, 10855, 10904, 10499,
       10420, 10802, 10855, 10499, 10405, 10335, 10337, 10831, 10543,
       10427, 10753, 10499, 10499, 10810, 10499, 10336, 10421, 10447,
       10499, 10831, 10405, 10461, 10758, 10669, 10436, 10499, 10874,
       10434, 10658, 10442, 10428, 10665, 10712, 10360, 10371, 10578,
       10855, 10499, 10600, 10434, 10806, 10499, 10842, 10499, 10412,
       10427, 10868, 10345, 10878, 10810, 10347, 10329, 10499, 10342,
       10831, 10427, 10405, 10430, 10887, 10352, 10802, 10382, 10855,
       10462, 10867, 10732, 10350, 10597, 10499, 10805, 10335, 10584,
       10335, 10462, 10335, 10440, 10605, 10423, 10408, 10337, 10438,
       10342, 10449, 10435, 10499, 10538, 10655, 10348, 10626, 10335,
       10432, 10710, 10855, 10493, 10401, 10446, 10499, 10831, 10782,
       10334, 10757, 10335, 10434, 10831, 10382, 10917, 10917, 10764,
       10855, 10855,

In [31]:
g = pred_4.astype(int)
g

array([10429, 10385, 10455, 10329, 10810, 10462, 10909, 10341, 10917,
       10890, 10421, 10469, 10459, 10428, 10855, 10855, 10917, 10499,
       10417, 10802, 10855, 10499, 10405, 10335, 10337, 10831, 10544,
       10427, 10705, 10499, 10499, 10810, 10499, 10335, 10421, 10451,
       10499, 10831, 10412, 10465, 10760, 10666, 10437, 10499, 10874,
       10434, 10658, 10441, 10428, 10656, 10710, 10360, 10373, 10579,
       10855, 10499, 10603, 10435, 10806, 10499, 10842, 10499, 10416,
       10425, 10868, 10345, 10878, 10802, 10347, 10329, 10499, 10343,
       10831, 10427, 10427, 10431, 10880, 10352, 10802, 10381, 10855,
       10462, 10867, 10732, 10350, 10599, 10499, 10805, 10336, 10583,
       10335, 10461, 10335, 10441, 10605, 10424, 10387, 10337, 10436,
       10342, 10449, 10436, 10499, 10537, 10653, 10348, 10626, 10335,
       10432, 10709, 10855, 10492, 10401, 10445, 10499, 10831, 10782,
       10334, 10757, 10335, 10435, 10831, 10382, 10917, 10917, 10774,
       10855, 10855,

In [32]:
c = (a, b, e, f, g)
d = pd.DataFrame(data=c)

In [33]:
pd.DataFrame(data=d.transpose()).to_csv("/content/drive/MyDrive/csv_file/prediksi_beras_SVR.csv")